// Parse test output into structured report

import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import type { DSAReport } from '../../types/report.js';

/**
 * Parse the DSA report file generated by test runner
 * @param reportFilePath - Path to .dsa-report.json file
 * @returns DSAReport object
 * @throws Error if file not found or invalid format
 */
export function parseReport(reportFilePath: string): DSAReport {
  const fullPath = resolve(reportFilePath);

  if (!existsSync(fullPath)) {
    throw new Error(
      `No report file found at: ${fullPath}\n` +
      'Run `dsa test` first to generate the report file.'
    );
  }

  try {
    const content = readFileSync(fullPath, 'utf-8');
    const report = JSON.parse(content) as Partial<DSAReport>;

    // Validate required fields
    if (typeof report.moduleId !== 'string') {
      throw new Error('Invalid report: missing or invalid "moduleId" field');
    }

    if (typeof report.summary !== 'string') {
      throw new Error('Invalid report: missing or invalid "summary" field');
    }

    if (typeof report.pass !== 'boolean') {
      throw new Error('Invalid report: missing or invalid "pass" field');
    }

    if (!Array.isArray(report.cases)) {
      throw new Error('Invalid report: missing or invalid "cases" array');
    }

    // Validate each test case
    for (const testCase of report.cases) {
      if (typeof testCase.subchallengeId !== 'string') {
        throw new Error('Invalid report: test case missing "subchallengeId"');
      }
      if (typeof testCase.passed !== 'boolean') {
        throw new Error('Invalid report: test case missing "passed" boolean');
      }
    }

    return report as DSAReport;
  } catch (error) {
    if (error instanceof SyntaxError) {
      throw new Error(
        `Invalid JSON in report file: ${error.message}\n` +
        `Report file: ${fullPath}`
      );
    }
    if (error instanceof Error && error.message.includes('Invalid report')) {
      throw error;
    }
    throw new Error(
      `Failed to parse report file: ${error instanceof Error ? error.message : 'Unknown error'}\n` +
      `Report file: ${fullPath}`
    );
  }
}
