// Test report type definitions

/**
 * Test case result from the test runner
 */
export interface TestCase {
  subchallengeId: string;  // Slug from filename (e.g., "create-class", "push")
  passed: boolean;          // true/false
  message?: string;         // Optional error message
}

/**
 * Report format generated by test runners (written to .dsa-report.json)
 * This is the standardized format that all test runners must produce
 */
export interface DSAReport {
  moduleId: string;        // e.g., "stack"
  summary: string;         // Human-readable summary (e.g., "4/5 tests passed")
  pass: boolean;           // Overall pass/fail
  cases: TestCase[];       // Per-sub-challenge results
}

/**
 * Legacy interface for internal CLI use (may be deprecated)
 */
export interface TestReport {
  pass: boolean;
  summary: string;
  details?: {
    total: number;
    passed: number;
    failed: number;
    failedTests?: string[];
  };
}

/**
 * Request payload for POST /api/submissions
 */
export interface SubmissionRequest {
  projectId: string;
  details: DSAReport;      // The full DSA report from test runner
  commitSha?: string;      // Git commit SHA (optional)
}

/**
 * Configuration loaded from dsa.config.json
 */
export interface ProjectConfig {
  projectId: string;
  projectToken: string;   // Auth token for API (not authToken!)
  moduleId: string;
  language: string;
  apiUrl: string;
  testCommand: string;     // Command to run tests (e.g., "node tests/run.js")
  reportFile: string;      // Path to report file (e.g., ".dsa-report.json")
}

